### PR TITLE
add allow_playback_repeats option to Cassette

### LINKED ISSUE #540: allow_playback_repeats
Ruby VCR has a Cassette option [allow_playback_repeats](https://relishapp.com/vcr/vcr/docs/request-matching/playback-repeats). Any chance this can be added to vcrpy?

### PR DESCRIPTION
**Pull request by tysonholub**
closes #540

### CODE REVIEW

**Comment by tysonholub** [comment]
Hi, this was a fairly simple feature to implement. Wondering if it will be merged in or not. Thanks!

**Comment by jairhenrique** [comment]
@tysonholub please rebase this code with master.

**Comment by jairhenrique** [comment]
@tysonholub can you add some docs about this option?

**Comment by tysonholub** [comment]
All set, thanks!

**Comment by jairhenrique** [comment]
@tysonholub great! Can you fix this lint error: https://travis-ci.org/github/kevin1024/vcrpy/jobs/708423571

@kevin1024 can you merge this PR after CI success?

**Comment by tysonholub** [comment]
Woops. Fixed

**Pull request merged**
