### PR TITLE
Enable testing on Python 3.12 & PyPy 3.9/3.10

### PR DESCRIPTION
**Pull request by mgorny**
As requested in https://github.com/kevin1024/vcrpy/issues/707#issuecomment-1662706535.

I've also noticed that PyPy3.9 and 3.10 were missing, so added them as well.

### CODE REVIEW

**Comment by jairhenrique** [comment]
@mgorny can you apply the patch suggested on #707

**Comment by mgorny** [comment]
> @mgorny can you apply the patch suggested on #707

I've done it in a slightly better way. However, I'm still not convinced it's the correct solution.

**Comment by mgorny** [comment]
The problem with aiohttp is that the current release's sdist has C files generated using old version of Cython. I've added a tox change that disables the C extension when building for 3.12, making it possible to install pure Python version of aiohttp for testing.

**Comment by mgorny** [comment]
I think the remaining test failures are (preexisting) flakiness and not related to my changes.

**Comment by jairhenrique** [comment]
LGTM.
@hartwork can you help with this review?

**Comment by hartwork** [comment]
@jairhenrique sorry, I lack bandwidth for this, I need to cut down my time on VCR.py for now.

**Pull request merged**
