### PR TITLE
Fix default port for HTTPS

### PR DESCRIPTION
**Pull request by abhinav**

### CODE REVIEW

**Comment by abhinav** [comment]
master may be broken. pypy-httplib2 fails on my local copy of master as well (without this change).

**Comment by IvanMalison** [comment]
Thanks. Did you look in to the test failure in the travis build?

**Comment by abhinav** [comment]
Yes. The issue seems to be that the headers can be out of order for the assertion. Added a fix.

**Comment by kevin1024** [comment]
Nice find!  What kind of bug did this cause?

**Comment by abhinav** [comment]
None that I'm aware of. Just stumbled into it. :)

**Pull request merged**
