### PR TITLE
Correct mock imports. Fixes #504

### LINKED ISSUE #504: python 3.8 vcrpy 4.0.1 No module named 'mock'
```
python3.8/site-packages/vcr/patch.py", line 5, in <module>
    import mock
ModuleNotFoundError: No module named 'mock'
```

my suggestion: everywhere in projects change:

import mock -> from unittest import mock

### PR DESCRIPTION
**Pull request by neozenith**
Fixes #504 

Change imports for importing `mock`

### CODE REVIEW

**Comment by neozenith** [comment]
Awaiting CI and will pull the trigger for the patch release in an hour or two.

**Comment by llybin** [comment]
I think need to delete mock here also: https://github.com/kevin1024/vcrpy/blob/master/tox.ini#L66
that why 4.0 was not failed.

**Comment by neozenith** [comment]
@llybin thanks for the quick reviews. This is really appreciated. 

The deleted imports earlier have been addressed. That was weird issue with VSCode, I saw when I reviewed the PR too.

Great catch with the tox import masking the issue.

**Comment by carlwgeorge** [comment]
Now that mock is no longer necessary, should it also be removed from [tests_require in setup.py](https://github.com/kevin1024/vcrpy/blob/accffa8ea2a2d1c9c89f840b67171b9046b6fe11/setup.py#L66)?

**Comment by llybin** [comment]
I think yes

**Pull request merged**
