### PR TITLE
Remove "vcrpy-unittest" section from docs

### PR DESCRIPTION
**Pull request by jedie**
https://github.com/agriffis/vcrpy-unittest is abandon

### CODE REVIEW

**Review by hartwork — COMMENTED** [review]
I believe it's time to pull the code from vcrpy-unittest in here instead, see #512. Could be two stages of course, first dropping this, and then re-adding it as two pull requests. @jairhenrique @kevin1024 what do you think?

**Comment by kevin1024** [comment]
Yeah makes sense to pull it in if it’s truly unmaintained and lots of folks are using it.  Paging @agriffis

**Comment by agriffis** [comment]
Makese sense to pull it in here. Please go ahead. I'm no longer using or maintaining it.

**Comment by agriffis** [comment]
I think maybe the reason it was a separate package was to avoid extra deps in this package, but I don't remember exactly. If someone wants to maintain the separate package, I could transfer the repo.

**Comment by jairhenrique** [comment]
@kevin1024 does it make sense for you to create an org on github and move vcrpy and this project into that org?

**Comment by hartwork** [comment]
> I think maybe the reason it was a separate package was to avoid extra deps in this package, but I don't remember exactly.

I see no additional runtime dependencies needed at https://github.com/agriffis/vcrpy-unittest/blob/master/setup.py#LL38C5-L38C21 .

My vote for inclusion so the test integration has a good chance to reach its users. As long as its separate, at least Linux distros will not have it, and its so close to core vcrpy and rather tiny, literally 44 lines in a single file https://github.com/agriffis/vcrpy-unittest/blob/master/vcr_unittest/testcase.py (if we ignore the testcases for the moment). Clear vote for inclusion from me.

**Comment by kevin1024** [comment]
All right, let’s bring it in!

**Comment by hartwork** [comment]
> All right, let’s bring it in!

Here you go: #712

**Comment by hartwork** [comment]
> All right, let’s bring it in!

Closing in favor of pull request #712 …

**Pull request closed without merging**
