### PR TITLE
Fix httplib endheaders if a message_body exists

### LINKED ISSUE #140: xmlrpclib support
`vcrpy` and `xmlrpclib` don't work together. Without vcr, the following code outputs tracker schema.

```
import vcr
import xmlrpclib

with vcr.use_cassette('xmlrpcvideo.yaml'):
  roundup_server = xmlrpclib.ServerProxy('http://bugs.python.org/xmlrpc', allow_none=True)
  print(roundup_server.schema())
```

With vcr it fails:

```
> python schema.py
Traceback (most recent call last):
  File "schema.py", line 6, in <module>
    print(roundup_server.schema())
  File "C:\Python27\Lib\xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "C:\Python27\Lib\xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "C:\Python27\Lib\xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Python27\Lib\xmlrpclib.py", line 1294, in single_request
    response = h.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'
```

### PR DESCRIPTION
**Pull request by Diaoul**
Fixes #140

### CODE REVIEW

**Comment by IvanMalison** [comment]
build failed.

Also, could you add a test?

**Comment by kevin1024** [comment]
I think the build failure was an accident.

**Comment by IvanMalison** [comment]
Yep. thats why i restarted it.

**Comment by Diaoul** [comment]
I would love to add a test but xmlrpc is currently untested and adding
tests would require to set up a fake xmlrpc server which would take more
time than I can currently invest.

Also I'm not too comfortable with vcrpy, I just started using it yesterday
and fixed a bug that made *my* tests fail (using vcrpy with xmlrpc).

**Comment by IvanMalison** [comment]
hmm okay. let me take a look to see if I can write a test for this.

**Comment by IvanMalison** [comment]
This change was included in 6cbc0fb2793b356ee97bd260724de95bb903b4c1. Everything should be fixed now. Tests were added too!

**Pull request closed without merging**
