### PR TITLE
support 3.6

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by kevin1024** [comment]
Thanks.  What about #294 - I think there are some changes needed around patching?

**Comment by graingert** [comment]
@kevin1024 meged in #294 and fixed a few other things. I think it will pass now.

**Comment by kevin1024** [comment]
Our tests are getting kinda slow huh :-P

I think I'm cool dropping tests for python3.3.  I think it's end-of-life for security updates anyway.

**Comment by mortenvp** [comment]
Hi guys, great you've got this merged. Sorry for newb question, but when do you expect an updated version will be available via pypi? Or what is the process?

**Comment by graingert** [comment]
@mortenvp I uploaded 1.11.0 to PyPI

**Pull request merged**
