### PR TITLE
Update aiohttp_stub to work with binary content

### PR DESCRIPTION
**Pull request by allisson**

### CODE REVIEW

**Comment by RadJamesway** [comment]
@kevin1024 is there anything I can do to help get this branch merged?  
@allisson is it possible that it needs a rebuild?  It looks like some of the errors might be related to older versions of flask 0.10

**Comment by kevin1024** [comment]
Sure, I'll click the rebuild button :)

**Comment by allisson** [comment]
Travis has one fail with python 3.6 and requests 2.3 -> https://travis-ci.org/kevin1024/vcrpy/jobs/342753029

**Comment by lamenezes** [comment]
@allisson thanks for your contribution. could you please update your branch?

**Comment by allisson** [comment]
@lamenezes https://www.youtube.com/watch?v=mPltmbBKP0s

**Comment by lamenezes** [comment]
:soccer: :top:

**Pull request merged**
