### PR TITLE
Aiohttp support

### PR DESCRIPTION
**Pull request by lamenezes**
Solves #209

### CODE REVIEW

**Comment by kevin1024** [comment]
😯wow!

**Comment by kevin1024** [comment]
Thanks for the contribution.  See if you can goof with the travis/pytest config so it only runs the aiohttp tests on python3.4+

**Comment by lamenezes** [comment]
The newest version of flake8 (>3) [1] does not support python 2.6, 3.2 and 3.3 and it is causing  this build to fail when running tests for py26-flakes

[1] https://flake8.pycqa.org/en/latest/release-notes/3.0.0.html

**Comment by kevin1024** [comment]
Heh ok.  See if you can disable flakes on py26 I'm that case

**Comment by lamenezes** [comment]
It finally passed :smile:

**Comment by drgarcia1986** [comment]
👏 👏 👏 
Thanks a lot @lamenezes

**Pull request merged**
