### PR TITLE
fix: correctly handle asyncio.run when loop exists

### PR DESCRIPTION
**Pull request by alekseik1**
This PR is a duplicate of #833 but:
- no new event loop is set, which this could break other libraries
- no thread pool is used - some folks might want have "how many threads did I create" checks in their tests

I tested this fix in my project with Starlette's `TestClient` - everything is working.

### CODE REVIEW

**Comment by jairhenrique** [comment]
@alekseik1 please rebase your branch with master.

**Comment by alekseik1** [comment]
@jairhenrique done

**Review by jairhenrique — APPROVED** [review]

**Comment by alekseik1** [comment]
@jairhenrique could you please help with merging this PR? I'd really appreciate if a new release with this fix comes after New Year holidays!

**Comment by alekseik1** [comment]
oh, forgot to mention issue this PR addresses, here it is: #628

**Pull request merged**
