### PR TITLE
Configure read the docs V2

### PR DESCRIPTION
**Pull request by jairhenrique**
Reference: https://blog.readthedocs.com/migrate-configuration-v2/

### CODE REVIEW

**Review by hartwork — COMMENTED** [review]
Hi @jairhenrique I have little to no experience with readthedocs and no account so my ability to do proper review here are limited. What I can say is that:
- `PYTHONPATH="$PWD" sphinx-build -a docs docs/html/` worked to build the docs locally with Sphinx 7.0.1. (There is one unrelated warning about it.)
- (We should probably have simple CI to catch build regressions on documentation.)
- We should probably use the pinning requirements feature to pin Sphinx to 7.0.1 for a stable build. (Dependabot and CI together will keep us in the present with it with little manual effort.)

So my vote for pinning Sphinx via a new file `docs/requirements.txt` at least. What do you think?

**Comment by hartwork** [comment]
> @hartwork I can add you as a documentation maintainer in RTD. Can I use the email in your github profile?

@jairhenrique please don't, I'm really far from a maintainer here, especially with regard to documentation. It would send the wrong message.

**Comment by jairhenrique** [comment]
@hartwork so, can I merge this pr?

**Comment by hartwork** [comment]
> @hartwork so, can I merge this pr?

@jairhenrique I cannot take responsibility for the decision myself due to not seeing the full picture, but no objections from me for merging if you are confident about it. Your call.

**Pull request merged**
