### PR TITLE
return values from generator decorator

### PR DESCRIPTION
**Pull request by graingert**
I broke this in my previous PR sorry!

Needs a test

### CODE REVIEW

**Comment by graingert** [comment]
I'm on my phone at the moment so it's tricky for me to add a test

**Comment by kevin1024** [comment]
No worries, ping me when fixed and I'll do another release.

**Comment by kevin1024** [comment]
Released in https://github.com/kevin1024/vcrpy/commit/1e3a5ac7530266a1b613336e84ad48884342d8a1

**Comment by graingert** [comment]
@kevin1024 test added

**Review by jairhenrique — APPROVED** [review]

**Pull request merged**
