### PR TITLE
Finish up on Python 3.12 support

### PR DESCRIPTION
**Pull request by hartwork**
Follow-up to #754

### CODE REVIEW

**Comment by jairhenrique** [comment]
@hartwork can you rebase with master!?

**Review by jairhenrique — APPROVED** [review]

**Comment by hartwork** [comment]
> @hartwork can you rebase with master!?

@jairhenrique sure, but it had little chance of working last time, hence the draft. Rebased and pushed.

**Comment by hartwork** [comment]
@jairhenrique I have re-run the pypy3.10 CI **10 times** now without a single success. I believe it's time to declare that support broken and drop it in a dedicated pull request, coming up in a minute. The errors were:

a) with `-m 'not online'` (most of the time)
```
[..]
E           urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
[..]
=========================== short test summary info ============================
FAILED tests/integration/test_urllib3.py::test_post[https] - urllib3.exceptio...
=========== 1 failed, 249 passed, 9 skipped, 14 deselected in 22.59s ===========
[..]
```

b) with `-m online` (rarely)

```
[..]
E           requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.flickr.com', port=443): Max retries exceeded with url: /services/upload (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00007fc8b1f54870>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[..]
=========================== short test summary info ============================
FAILED tests/integration/test_wild.py::test_flickr_should_respond_with_200 - ...[..]
===== 1 failed, 15 passed, 5 skipped, 293 deselected in 144.59s (0:02:24) ======
[..]

**Comment by hartwork** [comment]
@jairhenrique now that this is merged, I'll write an issue recommending a new release to unblock users' upgrade to Python 3.12. Will take a few minutes.

**Pull request merged**
