### PR TITLE
Add a `rewind` method to reset a cassette.

### PR DESCRIPTION
**Pull request by khamidou**
Hi!

First, thank you for building/maintaining vcrpy — it's a very useful library! 

I'm currently writing a unit test that has to use the same cassette twice, but it turns out that there isn't a function to "rewind" the cassette. It looks like other people are interested in this feature (#357) so I thought I'd send a quick PR to add it.

I've also written a small unit test to exercise it. Please let me know if you'd like me to expand on it.

Thank you!

### CODE REVIEW

**Comment by khamidou** [comment]
@lamenezes Sorry to bother you but I saw that you were merging PRs left and right 😅
What do you think about this PR? Are there any changes I should make?

**Comment by IvanMalison** [comment]
This looks fine to me.

**Comment by khamidou** [comment]
Thank you, @IvanMalison!

**Comment by vEpiphyte** [comment]
Thanks @IvanMalison @khamidou

**Pull request merged**
