### PR TITLE
Mark tests with @pytest.mark.online that need access to the Internet

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Review by hartwork — CHANGES_REQUESTED** [review]
Hi @jspricke, good idea!

When turning off Internet access and running all tests a la https://github.com/kevin1024/vcrpy/issues/645#issuecomment-1561933604 I get 106 failures.

<details>
<summary>106 failures, please click for details.</summary>

```
FAILED tests/integration/test_aiohttp.py::test_status[https]
FAILED tests/integration/test_aiohttp.py::test_status[http]
FAILED tests/integration/test_aiohttp.py::test_headers[https-None]
FAILED tests/integration/test_aiohttp.py::test_headers[https-auth1]
FAILED tests/integration/test_aiohttp.py::test_headers[http-None]
FAILED tests/integration/test_aiohttp.py::test_headers[http-auth1]
FAILED tests/integration/test_aiohttp.py::test_case_insensitive_headers[https]
FAILED tests/integration/test_aiohttp.py::test_case_insensitive_headers[http]
FAILED tests/integration/test_aiohttp.py::test_text[https]
FAILED tests/integration/test_aiohttp.py::test_text[http]
FAILED tests/integration/test_aiohttp.py::test_json[https]
FAILED tests/integration/test_aiohttp.py::test_json[http]
FAILED tests/integration/test_aiohttp.py::test_binary[https]
FAILED tests/integration/test_aiohttp.py::test_binary[http]
FAILED tests/integration/test_aiohttp.py::test_stream[https]
FAILED tests/integration/test_aiohttp.py::test_stream[http]
FAILED tests/integration/test_aiohttp.py::test_post[https-data]
FAILED tests/integration/test_aiohttp.py::test_post[https-json]
FAILED tests/integration/test_aiohttp.py::test_post[http-data]
FAILED tests/integration/test_aiohttp.py::test_post[http-json]
FAILED tests/integration/test_aiohttp.py::test_params[https]
FAILED tests/integration/test_aiohttp.py::test_params[http]
FAILED tests/integration/test_aiohttp.py::test_params_same_url_distinct_params[https]
FAILED tests/integration/test_aiohttp.py::test_params_same_url_distinct_params[http]
FAILED tests/integration/test_aiohttp.py::test_params_on_url[https]
FAILED tests/integration/test_aiohttp.py::test_params_on_url[http]
FAILED tests/integration/test_aiohttp.py::test_redirect[https]
FAILED tests/integration/test_aiohttp.py::test_redirect[http]
FAILED tests/integration/test_aiohttp.py::test_not_modified[https]
FAILED tests/integration/test_aiohttp.py::test_not_modified[http]
FAILED tests/integration/test_aiohttp.py::test_double_requests[https]
FAILED tests/integration/test_aiohttp.py::test_double_requests[http]
FAILED tests/integration/test_aiohttp.py::test_not_allow_redirects[https]
FAILED tests/integration/test_aiohttp.py::test_not_allow_redirects[http]
FAILED tests/integration/test_config.py::test_set_serializer_default_config[https]
FAILED tests/integration/test_config.py::test_set_serializer_default_config[http]
FAILED tests/integration/test_config.py::test_default_set_cassette_library_dir[https]
FAILED tests/integration/test_config.py::test_default_set_cassette_library_dir[http]
FAILED tests/integration/test_config.py::test_override_set_cassette_library_dir[https]
FAILED tests/integration/test_config.py::test_override_set_cassette_library_dir[http]
FAILED tests/integration/test_config.py::test_override_match_on[https]
FAILED tests/integration/test_config.py::test_override_match_on[http]
FAILED tests/integration/test_config.py::test_dont_record_on_exception[https]
FAILED tests/integration/test_config.py::test_dont_record_on_exception[http]
FAILED tests/integration/test_disksaver.py::test_disk_saver_nowrite[https]
FAILED tests/integration/test_disksaver.py::test_disk_saver_nowrite[http]
FAILED tests/integration/test_disksaver.py::test_disk_saver_write[https]
FAILED tests/integration/test_disksaver.py::test_disk_saver_write[http]
FAILED tests/integration/test_httplib2.py::test_effective_url
FAILED tests/integration/test_httpx.py::test_status[DoAsyncRequest-https]
FAILED tests/integration/test_httpx.py::test_status[DoAsyncRequest-http]
FAILED tests/integration/test_httpx.py::test_status[DoSyncRequest-https]
FAILED tests/integration/test_httpx.py::test_status[DoSyncRequest-http]
FAILED tests/integration/test_httpx.py::test_case_insensitive_headers[DoAsyncRequest-https]
FAILED tests/integration/test_httpx.py::test_case_insensitive_headers[DoAsyncRequest-http]
FAILED tests/integration/test_httpx.py::test_case_insensitive_headers[DoSyncRequest-https]
FAILED tests/integration/test_httpx.py::test_case_insensitive_headers[DoSyncRequest-http]
FAILED tests/integration/test_httpx.py::test_content[DoAsyncRequest-https]
FAILED tests/integration/test_httpx.py::test_content[DoAsyncRequest-http]
FAILED tests/integration/test_httpx.py::test_content[DoSyncRequest-https]
FAILED tests/integration/test_httpx.py::test_content[DoSyncRequest-http]
FAILED tests/integration/test_httpx.py::test_json[DoAsyncRequest-https]
FAILED tests/integration/test_httpx.py::test_json[DoAsyncRequest-http]
FAILED tests/integration/test_httpx.py::test_json[DoSyncRequest-https]
FAILED tests/integration/test_httpx.py::test_json[DoSyncRequest-http]
FAILED tests/integration/test_httpx.py::test_params_same_url_distinct_params[DoAsyncRequest-https]
FAILED tests/integration/test_httpx.py::test_params_same_url_distinct_params[DoAsyncRequest-http]
FAILED tests/integration/test_httpx.py::test_params_same_url_distinct_params[DoSyncRequest-https]
FAILED tests/integration/test_httpx.py::test_params_same_url_distinct_params[DoSyncRequest-http]
FAILED tests/integration/test_httpx.py::test_redirect[DoAsyncRequest-https]
FAILED tests/integration/test_httpx.py::test_redirect[DoAsyncRequest-http]
FAILED tests/integration/test_httpx.py::test_redirect[DoSyncRequest-https]
FAILED tests/integration/test_httpx.py::test_redirect[DoSyncRequest-http]
FAILED tests/integration/test_httpx.py::test_work_with_gzipped_data[DoAsyncRequest-https]
FAILED tests/integration/test_httpx.py::test_work_with_gzipped_data[DoAsyncRequest-http]
FAILED tests/integration/test_httpx.py::test_work_with_gzipped_data[DoSyncRequest-https]
FAILED tests/integration/test_httpx.py::test_work_with_gzipped_data[DoSyncRequest-http]
FAILED tests/integration/test_httpx.py::test_simple_fetching[DoAsyncRequest-https://github.com/kevin1024/vcrpy/issues/3]
FAILED tests/integration/test_httpx.py::test_simple_fetching[DoAsyncRequest-https://github.com/kevin1024/vcrpy/issues/4]
FAILED tests/integration/test_httpx.py::test_simple_fetching[DoAsyncRequest-https://github.com/kevin1024/vcrpy/issues/5]
FAILED tests/integration/test_httpx.py::test_simple_fetching[DoSyncRequest-https://github.com/kevin1024/vcrpy/issues/3]
FAILED tests/integration/test_httpx.py::test_simple_fetching[DoSyncRequest-https://github.com/kevin1024/vcrpy/issues/4]
FAILED tests/integration/test_httpx.py::test_simple_fetching[DoSyncRequest-https://github.com/kevin1024/vcrpy/issues/5]
FAILED tests/integration/test_httpx.py::test_cookies[DoAsyncRequest-https]
FAILED tests/integration/test_httpx.py::test_cookies[DoAsyncRequest-http]
FAILED tests/integration/test_httpx.py::test_cookies[DoSyncRequest-https]
FAILED tests/integration/test_httpx.py::test_cookies[DoSyncRequest-http]
FAILED tests/integration/test_httpx.py::test_relative_redirects[DoAsyncRequest-https]
FAILED tests/integration/test_httpx.py::test_relative_redirects[DoAsyncRequest-http]
FAILED tests/integration/test_httpx.py::test_relative_redirects[DoSyncRequest-https]
FAILED tests/integration/test_httpx.py::test_relative_redirects[DoSyncRequest-http]
FAILED tests/integration/test_httpx.py::test_redirect_wo_allow_redirects[DoAsyncRequest-https]
FAILED tests/integration/test_httpx.py::test_redirect_wo_allow_redirects[DoAsyncRequest-http]
FAILED tests/integration/test_httpx.py::test_redirect_wo_allow_redirects[DoSyncRequest-https]
FAILED tests/integration/test_httpx.py::test_redirect_wo_allow_redirects[DoSyncRequest-http]
FAILED tests/integration/test_register_matcher.py::test_registered_true_matcher[https]
FAILED tests/integration/test_register_matcher.py::test_registered_true_matcher[http]
FAILED tests/integration/test_register_matcher.py::test_registered_false_matcher[https]
FAILED tests/integration/test_register_matcher.py::test_registered_false_matcher[http]
FAILED tests/integration/test_urllib2.py::test_effective_url
FAILED tests/integration/test_urllib3.py::test_redirects
FAILED tests/integration/test_wild.py::test_flickr_should_respond_with_200
FAILED tests/integration/test_wild.py::test_amazon_doctype
FAILED tests/unit/test_stubs.py::TestVCRConnection::testing_connect
FAILED tests/unit/test_unittest.py::test_get_vcr_with_matcher
FAILED tests/unit/test_unittest.py::test_testcase_playback
```

</details>

With a rebased version of this pulll request on top and adding `-m online` to the pytest call, that list goes down to 6 failures.

<details>
<summary>6 failures, please click for details.</summary>

```
FAILED tests/integration/test_httplib2.py::test_effective_url
FAILED tests/integration/test_urllib2.py::test_effective_url
FAILED tests/integration/test_urllib3.py::test_redirects
FAILED tests/integration/test_wild.py::test_flickr_should_respond_with_200
FAILED tests/integration/test_wild.py::test_amazon_doctype
FAILED tests/unit/test_stubs.py::TestVCRConnection::testing_connect
```

</details>


Would you be up for marking these tests as `online` also so that we get down to 0 failures for current `master`?

**Comment by jspricke** [comment]
> When turning off Internet access and running all tests a la [#645 (comment)](https://github.com/kevin1024/vcrpy/issues/645#issuecomment-1561933604) I get 106 failures.

Interesting, we run those test automatically in Debian already:
https://buildd.debian.org/status/fetch.php?pkg=vcr.py&arch=all&ver=4.2.1-1&stamp=1671217645&raw=0

> With a rebased version of this pulll request on top and adding `-m online` to the pytest call, that list goes down to 6 failures.
> Would you be up for marking these tests as `online` also so that we get down to 0 failures for current `master`?

Those tests are exactly what this patch marks as `online` already, you probably want `-m "not online"`, can you give it a try?

**Comment by hartwork** [comment]
Hi @jspricke,

> > When turning off Internet access and running all tests a la [#645 (comment)](https://github.com/kevin1024/vcrpy/issues/645#issuecomment-1561933604) I get 106 failures.
> 
> Interesting, we run those test automatically in Debian already: https://buildd.debian.org/status/fetch.php?pkg=vcr.py&arch=all&ver=4.2.1-1&stamp=1671217645&raw=0

I'm not sure what to look for on that page or what the message is. Are you saying that Debian should be running fewer tests than currently because more are using the Internet than assumed previously?
Btw vcrpy in Gentoo could also benefit from a the online flag to get rid of the exclusion file list at https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/vcrpy/vcrpy-4.3.1.ebuild#n44 .

> 
> > With a rebased version of this pulll request on top and adding `-m online` to the pytest call, that list goes down to 6 failures.
> > Would you be up for marking these tests as `online` also so that we get down to 0 failures for current `master`?
> 
> Those tests are exactly what this patch marks as `online` already, you probably want `-m "not online"`, can you give it a try?

Good point! When I flip things around to  `-m "not online"` I get 100 failed tests now which seems to make sense given that 100 + 6 = 106, the total number of tests failing without Internet Access on `master`. I think that means we would need to mark 100 tests more rather than 6 more?

**Comment by jspricke** [comment]
> I'm not sure what to look for on that page or what the message is. Are you saying that Debian should be running fewer tests than currently because more are using the Internet than assumed previously?

My point was that all those tests in the log work without internet (at least with Debian tooling).

> Good point! When I flip things around to `-m "not online"` I get 100 failed tests now which seems to make sense given that 100 + 6 = 106, the total number of tests failing without Internet Access on `master`. I think that means we would need to mark 100 tests more rather than 6 more?

As shown in the Debian log, I only had to mark those 6 tests. Could you share your setup to find out why more tests are failing?

**Comment by hartwork** [comment]
> My point was that all those tests in the log work without internet (at least with Debian tooling).

@jspricke I see. How is Debian taking away Internet access technically? Are they starting a new Linux network namespace or is it using `LD_PRELOAD` or `LD_AUDIT` or …? Do you have links to how this technology works?

> As shown in the Debian log, I only had to mark those 6 tests. Could you share your setup to find out why more tests are failing?

My setup was literally pulling the LAN cable and disconnecting Wifi, nothing more. I'd expect that test oracle to be quite accurate though.

**Comment by jspricke** [comment]
> @jspricke I see. How is Debian taking away Internet access technically? Are they starting a new Linux network namespace or is it using `LD_PRELOAD` or `LD_AUDIT` or …? Do you have links to how this technology works?

There is `pbuilder` that uses iptables and `sbuild --chroot-mode=unshare` that uses user namespaces.

Actually I did not see the other test failures cause some tests where ignored already:

https://sources.debian.org/src/vcr.py/4.2.1-1/debian/rules/#L5

Sorry for not noticing that earlier.

I've updated the PR, can you give it an other try? (I'm currently running into unrelated test failures with the latest master).

**Review by hartwork — CHANGES_REQUESTED** [review]
> > @jspricke I see. How is Debian taking away Internet access technically? Are they starting a new Linux network namespace or is it using `LD_PRELOAD` or `LD_AUDIT` or …? Do you have links to how this technology works?
> 
> There is `pbuilder` that uses iptables and `sbuild --chroot-mode=unshare` that uses user namespaces.
> 
> Actually I did not see the other test failures cause some tests where ignored already:
> 
> https://sources.debian.org/src/vcr.py/4.2.1-1/debian/rules/#L5
> 
> Sorry for not noticing that earlier.

@jspricke no worries, thanks for elaborating.


> I've updated the PR, can you give it an other try? (I'm currently running into unrelated test failures with the latest master).

I have tried with the latest changes locally now and it looks like just the right 106 tests get selected/deselect by `-m online` and `-m 'not online'` now. Very nice, thanks for doing the leg work on this and for this improvement in general :+1: 

isort has two last tiny suggestions for adjustment at https://github.com/kevin1024/vcrpy/actions/runs/5299720625/jobs/9600399603#step:5:48 .  Could you run `isort . --overwrite-in-place` locally and update the pull request according to make the CI happy?

**Comment by jspricke** [comment]
> isort has two last tiny suggestions for adjustment at https://github.com/kevin1024/vcrpy/actions/runs/5299720625/jobs/9600399603#step:5:48 . Could you run `isort . --overwrite-in-place` locally and update the pull request according to make the CI happy?

Done.

**Comment by hartwork** [comment]
> Done.

@jspricke thanks, let's see how the CI likes it…

**Review by hartwork — APPROVED** [review]

**Comment by hartwork** [comment]
@jspricke PS: I [made Gentoo use the new `-m "not online"`](https://github.com/gentoo/gentoo/blob/68ab5e8e2427d8802ee46fa8b185160f7db5abfd/dev-python/vcrpy/vcrpy-4.4.0.ebuild#L43-L51) now. With too recent werkzeug in the environment these five tests will still fail, in case you run into that, too:
```
FAILED tests/integration/test_urllib2.py::test_random_body[http]
FAILED tests/integration/test_urllib2.py::test_random_body[https]
FAILED tests/integration/test_urllib2.py::test_multiple_requests[https]
FAILED tests/integration/test_urllib2.py::test_multiple_requests[http]
FAILED tests/integration/test_record_mode.py::test_new_episodes_record_mode_two_times
```

**Pull request merged**
