### PR TITLE
Adding support for boto3

### PR DESCRIPTION
**Pull request by dedsm**
boto3 bundles the requests library, so this basically is a copy and paste of the requests stubbing.

I'm a little lost in the testing of this, with some guidance and/or help I could complete this.

### CODE REVIEW

**Comment by kevin1024** [comment]
This looks great!  Just needs a test or two.  You can see how I tested boto in tests/integration/test_boto.py

**Comment by fxfitz** [comment]
@dedsm: Any luck on adding some tests for this? Right now we're using Placebo since vcrpy doesn't support boto3, and we keep running into problem after problem with placebo, so I'd like to switch to vcrpy if we can.

Sadly the placebo maintainer hasn't been very active as of late. :-/

**Comment by kevin1024** [comment]
@fxfitz does the code in this branch work for your use case with boto3?  Not too excited about adding this untested but if the code is working...

**Comment by dedsm** [comment]
it's still my intent to make the tests for this, all I need is some time and now I'm a little swamped, I've been using this since I did the PR and I've had no issues so far

**Comment by icanblink** [comment]
@dedsm i'll try to write some tests, as i need this integrated. is it ok?

**Comment by dedsm** [comment]
of course @icanblink be my guest, IMHO is basic copy/paste mostly

**Comment by icanblink** [comment]
@kevin1024 running `tox` fails with
`import vcr`
`E  ImportError: No module named vcr`
having this `name='vcrpy',` in `setup.py` .
am i doing something wrong?

**Comment by dedsm** [comment]
merged @icanblink changes and rebased with latest master code

**Comment by fxfitz** [comment]
Hmm.... tests are failing, but so is `master`... thoughts, @kevin1024?

(FWIW, I haven't tried this locally)

**Comment by kevin1024** [comment]
Yeah, something weird going on with those 2 tests on master.  Please ignore.  Or fix if you have time :-P

**Comment by foobarna** [comment]
The requests/httplib/tornado tests are failing with a 400/500 error code.
The boto/boto3 tests are failing due to credentials, as they are not included in tests but are passing locally.

I have in plan to make a PR fixing the tests, but when time allows it. :)

**Comment by fxfitz** [comment]
@foobarna Just to make sure you're not doing some rework, take a look at #258. I'll be listing details/fixes there as I come up with them.

**Comment by foobarna** [comment]
@fxfitz will do!

**Comment by foobarna** [comment]
fixed the tests in #260 (closing #258 ) and hopefully having this integrated

**Comment by kevin1024** [comment]
Merged #260 - please rebase this and see if the tests pass :+1:

**Comment by foobarna** [comment]
@dedsm can you please make another rebase?

**Comment by dedsm** [comment]
sorry, was out for the weekend, rebased now

**Comment by foobarna** [comment]
I have no idea why that test is failing in the 2 envs, all passes locally (and in #260)

**Comment by kevin1024** [comment]
@nickdirienzo can you check that failing test out?  I think that's the one you recently added.

**Comment by nickdirienzo** [comment]
@kevin1024 checking.

**Comment by nickdirienzo** [comment]
Hm... quickly checked against latest master, it seems to be passing consistently locally. However, based on the build history I'm dubious, so I'll dig deeper tonight.

**Comment by foobarna** [comment]
@kevin1024 having #261 for the failing test, can this PR be integrated?

**Comment by kevin1024** [comment]
OK, thanks for the contribution!

**Comment by eligundry** [comment]
@kevin1024 is there a timeline for when this will be pushed to pypi?

**Comment by kevin1024** [comment]
Soon - thanks for the ping.  Send me a reminder this weekend and I can probably get a release out :)

**Comment by fxfitz** [comment]
It's the weekend! :-D

Thanks, kevin!

**Comment by kevin1024** [comment]
OK, new release is out, 1.9.0

Thanks for your contribution :)

**Pull request merged**
