### PR TITLE
Fix in a check for requests compatibility import desired names

### LINKED ISSUE #215: make robust to having older requests available
Currently on jessie (with requests 2.4.3) if vcr.py (1.7.3) is installed via pip use of `vcr.use_cassette` would fail with
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/buildbot/datalad-pr-docker-dl-nd80/build/datalad/tests/utils.py", line 508, in newfunc
    return func(*args, **kwargs)
  File "/home/buildbot/datalad-pr-docker-dl-nd80/build/venv-ci/local/lib/python2.7/site-packages/vcr/cassette.py", line 95, in __call__
    function, args, kwargs
  File "/home/buildbot/datalad-pr-docker-dl-nd80/build/venv-ci/local/lib/python2.7/site-packages/vcr/cassette.py", line 103, in _execute_function
    return handler(function, args, kwargs)
  File "/home/buildbot/datalad-pr-docker-dl-nd80/build/venv-ci/local/lib/python2.7/site-packages/vcr/cassette.py", line 129, in _handle_function
    with self as cassette:
  File "/home/buildbot/datalad-pr-docker-dl-nd80/build/venv-ci/local/lib/python2.7/site-packages/vcr/cassette.py", line 82, in __enter__
    return next(self.__finish)
  File "/home/buildbot/datalad-pr-docker-dl-nd80/build/venv-ci/local/lib/python2.7/site-packages/vcr/cassette.py", line 50, in _patch_generator
    for patcher in CassettePatcherBuilder(cassette).build():
  File "/home/buildbot/datalad-pr-docker-dl-nd80/build/venv-ci/local/lib/python2.7/site-packages/vcr/patch.py", line 90, in build
    self._httplib(), self._requests(), self._urllib3(),
  File "/home/buildbot/datalad-pr-docker-dl-nd80/build/venv-ci/local/lib/python2.7/site-packages/vcr/patch.py", line 165, in _requests
    from .stubs import requests_stubs
  File "/home/buildbot/datalad-pr-docker-dl-nd80/build/venv-ci/local/lib/python2.7/site-packages/vcr/stubs/requests_stubs.py", line 3, in <module>
    from requests.packages.urllib3.connectionpool import HTTPConnection, VerifiedHTTPSConnection
ImportError: cannot import name HTTPConnection
```
even if I don't actually care/use requests.

### PR DESCRIPTION
**Pull request by yarikoptic**
i.e. HTTPConnection, VerifiedHTTPSConnection

Closes #215

### CODE REVIEW

**Comment by yarikoptic** [comment]
interesting, travis fails only with python3.4 and requests2.3

**Comment by IvanMalison** [comment]
@yarikoptic ping

**Comment by agriffis** [comment]
I merged #223 instead of this... If that was the wrong approach then please reopen, thanks!

**Comment by yarikoptic** [comment]
whatever works! ;) thanks!

**Pull request closed without merging**
