### PR TITLE
Record on exception (continuation of PR #237)

### LINKED ISSUE #205: Don't save requests from decorated tests if decorated test fails
As the title says: Don't save requests from decorated tests if decorated test fails

Does VCR already do this? If so awesome, and you guys should definitely say so in the README somewhere. Otherwise this seems like a solid feature. We have one test in particular where our 3rd party goes down more often than I'd care to admit, and if that bad response gets saved that will be quite aggravating.

### PR DESCRIPTION
**Pull request by Terseus**
Fixes #205 
Closes #237

This is a continuation of the PR #237.
Given that the author @dan-passaro didn't answered in 3 years, I considered a good idea to take over their branch and make it able to be merged.

@neozenith since you reviewed #237 I'll await for your comments.

### CODE REVIEW

**Comment by neozenith** [comment]
I’ll delegate review to @jairhenrique as they seem to be the most recent active contributor. 

Unfortunately I have other priorities come up and I’m no longer involved in this project sorry.

**Comment by jairhenrique** [comment]
@Terseus please, update the docs with this new param.

**Comment by Terseus** [comment]
Of course, I'll look into it.

Also will check what's happening with the pipeline, it worked on my machine™.

**Comment by Terseus** [comment]
Hi @jairhenrique

It turns out, it didn't worked in my machine after all :)
I had a bug in my setup and the tests for pypy3 were skipped.

After that found out that the fail was because a bug introduced by the `record_on_exception` implementation in Pypy, it should be fixed now.
Also I'd added a small section on how to use it in the "Advanced Features" page.

**Comment by jairhenrique** [comment]
@Terseus I fix the CI error. Can you rebase with master again!?

**Comment by Terseus** [comment]
@jairhenrique Sure, done.

**Comment by jairhenrique** [comment]
@Terseus thanks!

**Pull request merged**
