### PR TITLE
Ensure body is consumed only once (alternative to #851)

### PR DESCRIPTION
**Pull request by sathieu**
Fixes: #846

### CODE REVIEW

**Comment by sathieu** [comment]
@hartwork Please take a look at this PR :pray: .

**Comment by hartwork** [comment]
@sathieu I had a quick look and I think understand the problem now but from a quick look the patch raises questions, may not be the best place to patch yet, and is also lacking a new test to both document and regression-protect the case that it's fixing. I have other priorities at the moment, I won't be able to help more at the moment, thanks for your understanding.

**Review by hartwork — CHANGES_REQUESTED** [review]
Marking as "Changes requested" due to CI failing at multiple places and the comment above (in particular a missing test)…

**Comment by sathieu** [comment]
Thanks @hartwork I've fixed CI and added tests. Back to you :ping_pong: !

**Comment by hartwork** [comment]
Superseded by just-merged #851, closing…

**Pull request closed without merging**
