### PR TITLE
Add Path handling vcrpy

### PR DESCRIPTION
**Pull request by 07pepa**
* use cassette now handles str and Paths
* default filesystem.py persister hanles now Path and str
* added test  to cover accepting Paths as well

### CODE REVIEW

**Comment by jairhenrique** [comment]
@07pepa can you fix the lint error.

```
  lint run-test: commands[1] | black --check --diff .
  --- tests/unit/test_vcr.py	2022-10-09 13:55:56.205379 +0000
  +++ tests/unit/test_vcr.py	2022-10-09 13:56:18.955592 +0000
  @@ -363,7 +363,8 @@
   del test_dynamically_added
   
   
   def test_path_class_as_cassette():
       with use_cassette(
  -            Path(__file__).parent.parent.joinpath("integration/cassettes/test_httpx_test_test_behind_proxy.yml")):
  +        Path(__file__).parent.parent.joinpath("integration/cassettes/test_httpx_test_test_behind_proxy.yml")
  +    ):
           pass
  would reformat tests/unit/test_vcr.py
  
  Oh no! 💥 💔 💥
  1 file would be reformatted, 70 files would be left unchanged.
  Error: ERROR: InvocationError for command /home/runner/work/vcrpy/vcrpy/.tox/lint/bin/black --check --diff . (exited with code 1)
```

**Comment by 07pepa** [comment]
will do

**Comment by 07pepa** [comment]
fixed please merge

**Comment by jairhenrique** [comment]
@07pepa please, rebase your branch with master, I'll do the merge after that.

**Comment by 07pepa** [comment]
rebased

Thanks

**Comment by jairhenrique** [comment]
Thanks.

**Pull request merged**
