### PR TITLE
Allow triggering CI manually

### PR DESCRIPTION
**Pull request by hartwork**
I have needed this myself for #699 [before](https://github.com/kevin1024/vcrpy/actions/runs/4996820803) and #700 seems to be an indicator of the same thing. @jairhenrique does this look like the right move?

### CODE REVIEW

**Comment by jairhenrique** [comment]
@hartwork this change duplicates the pipe on PR. This change is not necessary.

image

**Comment by hartwork** [comment]
@jairhenrique yes it does. Is it a problem though? Other ideas? We both wanted to run CI in outside of a pull request which is currently not possible, so I believe some change would be great.

**Comment by jairhenrique** [comment]
@hartwork we can enable manual dispatch. https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

```yaml
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
```

**Comment by hartwork** [comment]
@jairhenrique that's an option, should I make the pull request do that?

**Comment by hartwork** [comment]
@jairhenrique done, what do you think?

**Review by jairhenrique — APPROVED** [review]
LGTM! 🚀

**Comment by hartwork** [comment]
@jairhenrique cool! I'll re-run the CI until green and merge on success, at least that's the plan :smiley:

**Pull request merged**
