### PR TITLE
Fix for #174 to prevent filters from corrupting request

### PR DESCRIPTION
**Pull request by abramclark**
Replaces https://github.com/kevin1024/vcrpy/pull/687/

### CODE REVIEW

**Comment by abramclark** [comment]
> black formatting is not clean

Uhg I always use `black -S`. Should be fixed now.

**Comment by hartwork** [comment]
@abramclark please not that environment `py3*-aiohttp` is unfortunately a bit flaky, that's not your fault, I will restart it until green, just so you know.

**Comment by abramclark** [comment]
lol

**Comment by hartwork** [comment]
> lol

@abramclark I think crying would be more to the point :smile: In case you have time to track it down and make it rebust, that could make a great pull request, hint hint :smiley:

**Review by hartwork — COMMENTED** [review]
Commenting to get rid of the "changes requested" status…

**Review by hartwork — COMMENTED** [review]
Commenting to get rid of the "changes requested" status… — second try

**Review by hartwork — APPROVED** [review]
Only superficial review done, needs more review asking "is this the right fix". Thanks!

**Comment by hartwork** [comment]
@kevin1024 @jairhenrique does this PR look like a good move to you? Any concerns?

**Review by jairhenrique — APPROVED** [review]
LGTM.

**Pull request merged**
